const ProductData = [
    {
        id:1,
        name:"Bán nhà Phố Trạm 120m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "./pic7.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '120' ,
        bedroom: '3 phòng',
        bathroom: '2 phòng',
    },
    {
        id:2,
        name:"Bán nhà Phố Trạm 120m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "./pic6.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '120' ,
        bedroom: '3 phòng',
        bathroom: '2 phòng',
    },
    {
        id:3,
        name:"Bán nhà Phố Trạm 120m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "./pic5.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '120' ,
        bedroom: '3 phòng',
        bathroom: '2 phòng',
    },
    {
        id:4,
        name:"Bán nhà Phố Trạm 120m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "./pic4.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '120' ,
        bedroom: '3 phòng',
        bathroom: '2 phòng',
    },
    {
        id:5,
        name:"Bán nhà Phố Trạm 120m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "./pic1.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '120' ,
        bedroom: '3 phòng',
        bathroom: '2 phòng',
    },
    {
        id:6,
        name:"Bán nhà Phố Trạm 120m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "./pic2.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '120' ,
        bedroom: '3 phòng',
        bathroom: '2 phòng',
    },
    {
        id:7,
        name:"Bán nhà Phố Trạm 120m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "./pic3.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '120' ,
        bedroom: '3 phòng',
        bathroom: '2 phòng',
    },
    {
        id:8,
        name:"Bán nhà Phố Trạm 120m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "./pic4.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '120' ,
        bedroom: '3 phòng',
        bathroom: '2 phòng',
    },
    {
        id:9,
        name:"Bán nhà Phố Trạm 120m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "./pic1.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '120' ,
        bedroom: '3 phòng',
        bathroom: '2 phòng',
    },
    {
        id:10,
        name:"Bán nhà Phố Trạm 120m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "./pic2.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '120' ,
        bedroom: '3 phòng',
        bathroom: '2 phòng',
    },
    {
        id:11,
        name:"Bán nhà Phố Trạm 120m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "./pic3.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '120' ,
        bedroom: '3 phòng',
        bathroom: '2 phòng',
    },
    {
        id:12,
        name:"Bán nhà Phố Trạm 120m2 5 tầng 3.3 tỷ nhà mới. Gần ô tỏa",
        image: "./pic4.jpg",
        location:"Long Biên, Hà Nội",
        price: '3.3 tỷ' ,
        superficiality: '120' ,
        bedroom: '3 phòng',
        bathroom: '2 phòng',
    },
];

export default ProductData;
